name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - "index.html"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      # (Optional) Add any build steps here if you need to generate site files.
      # For a basic single-page site, there's nothing else to do.

      - name: Upload site artifact
        uses: actions/upload-artifact@v4
        with:
          # This is what your artifact will be called
          name: pages
          # '.' if your index.html is at the root of the repo
          path: .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          artifact_name: pages
