name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - "index.html"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      # Upload the repository content (including index.html) as a Pages artifact
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # '.' means "upload everything in the repository root"
          # If you build or generate your site into a subfolder, specify that instead.
          path: .
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
