name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - "index.html"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      # (Optional) If you have a build step (e.g., npm run build), do it here.
      # For a basic static site, there's no build step needed.

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          # Give the artifact a name (e.g., "my-pages-artifact").
          name: my-pages-artifact
          # Path to your final website files. '.' if your index.html is at the root.
          path: .

  deploy:
    # This job depends on the "build" job
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          # Match the artifact name used in the "build" job above.
          artifact_name: my-pages-artifact
