name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - "index.html"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      # If you needed to build a static site (e.g., using Jekyll, Hugo, etc.),
      # you would do that here. For this example, we don't have a build step.
      - name: Upload production artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: .
          # '.' represents the entire repository directory (including index.html)

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
